routes/web.php
<?php

//ФРОНТ ЧАСТЬ
/** Главная страница **/
Route::get('/', 'FrontPageController@index');

/* Текст договора */
Route::get('/oferta', 'FrontPageController@oferta');
Route::get('/oferta_kz', 'FrontPageController@oferta_kz');

/** Маршрут на страницу авторизации и регистрации */
Route::get('/auth', 'FrontPageController@auth');
Route::get('/user-register', 'FrontPageController@register');

Route::post('/register_post', 'FrontPageController@POSTregister');
Route::post('/auth_post', 'FrontPageController@POSTauth');

Route::get('/front-logout', 'FrontPageController@logout');

Route::get('/proffession/{id}', 'FrontPageController@jobPage');

Route::get('/search', 'FrontPageController@searchPage');

Route::get('/mentor_page/{id}', 'FrontPageController@mentorPage');


Route::group(['middleware' => ['auth.mentor'], 'prefix' => 'mentor'], function () {

    Route::any("/profile", "Mentor\MentorPageController@getProfile");
    Route::post("/profile-update-post", "Mentor\MentorPageController@profileUpdatePost");

});

Route::group(['middleware' => ['auth.user'], 'prefix' => 'user'], function () {

    Route::any("/profile", "User\UserPageController@getProfile");
    Route::post("/profile-update-post", "User\UserPageController@profileUpdatePost");

});




//БЭК ЧАСТЬ
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Mentors
    Route::delete('mentors/destroy', 'MentorsController@massDestroy')->name('mentors.massDestroy');
    Route::post('mentors/media', 'MentorsController@storeMedia')->name('mentors.storeMedia');
    Route::post('mentors/ckmedia', 'MentorsController@storeCKEditorImages')->name('mentors.storeCKEditorImages');
    Route::resource('mentors', 'MentorsController');

    // Clients
    Route::delete('clients/destroy', 'ClientsController@massDestroy')->name('clients.massDestroy');
    Route::post('clients/media', 'ClientsController@storeMedia')->name('clients.storeMedia');
    Route::post('clients/ckmedia', 'ClientsController@storeCKEditorImages')->name('clients.storeCKEditorImages');
    Route::resource('clients', 'ClientsController');

    // Jobs
    Route::delete('jobs/destroy', 'JobsController@massDestroy')->name('jobs.massDestroy');
    Route::post('jobs/media', 'JobsController@storeMedia')->name('jobs.storeMedia');
    Route::post('jobs/ckmedia', 'JobsController@storeCKEditorImages')->name('jobs.storeCKEditorImages');
    Route::resource('jobs', 'JobsController');

    // Locations
    Route::delete('locations/destroy', 'LocationsController@massDestroy')->name('locations.massDestroy');
    Route::resource('locations', 'LocationsController');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
});

app/Mentor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Mentor extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'mentors';

    protected $appends = [
        'photo',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public static $searchable = [
        'age',
        'approved',
        'price',
        'about',
        'rating',
        'date_1',
        'online',
        'date_5',
        'date_4',
        'date_3',
        'date_2',
        'offline',
        'useful_3',
        'useful_2',
        'contacts',
        'useful_1',
        'education',
        'job_place',
        'speciality',
        'job_experience',
    ];

    protected $fillable = [
        'age',
        'approved',
        'price',
        'about',
        'rating',
        'online',
        'date_5',
        'date_4',
        'date_3',
        'date_2',
        'date_1',
        'user_id',
        'offline',
        'useful_2',
        'useful_3',
        'useful_1',
        'contacts',
        'education',
        'job_place',
        'speciality',
        'created_at',
        'updated_at',
        'deleted_at',
        'location_id',
        'job_experience',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getPhotoAttribute()
    {
        $file = $this->getMedia('photo')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }

    public function jobs()
    {
        return $this->belongsToMany(Job::class);
    }

    public function location()
    {
        return $this->belongsTo(Location::class, 'location_id');
    }
}

app/Http/Controllers/Admin/MentorsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyMentorRequest;
use App\Http\Requests\StoreMentorRequest;
use App\Http\Requests\UpdateMentorRequest;
use App\Job;
use App\Location;
use App\Mentor;
use App\User;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class MentorsController extends Controller
{
    use MediaUploadingTrait;

    public function index(Request $request)
    {
        if ($request->ajax()) {
            $query = Mentor::with(['user', 'jobs', 'location'])->select(sprintf('%s.*', (new Mentor)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'mentor_show';
                $editGate      = 'mentor_edit';
                $deleteGate    = 'mentor_delete';
                $crudRoutePart = 'mentors';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('approved', function ($row) {
                return $row->approved ? "YES" : "NO";
            });
            $table->addColumn('user_email', function ($row) {
                return $row->user ? $row->user->email : '';
            });

            $table->editColumn('photo', function ($row) {
                if ($photo = $row->photo) {
                    return sprintf(
                        '<a href="%s" target="_blank"><img src="%s" width="50px" height="50px"></a>',
                        $photo->url,
                        $photo->thumbnail
                    );
                }

                return '';
            });
            $table->editColumn('job', function ($row) {
                $labels = [];

                foreach ($row->jobs as $job) {
                    $labels[] = sprintf('<span class="label label-info label-many">%s</span>', $job->name);
                }

                return implode(' ', $labels);
            });
            $table->editColumn('job_place', function ($row) {
                return $row->job_place ? $row->job_place : "";
            });
            $table->editColumn('education', function ($row) {
                return $row->education ? $row->education : "";
            });
            $table->editColumn('price', function ($row) {
                return $row->price ? $row->price : "";
            });
            $table->addColumn('location_name', function ($row) {
                return $row->location ? $row->location->name : '';
            });

            $table->editColumn('age', function ($row) {
                return $row->age ? $row->age : "";
            });

            $table->rawColumns(['actions', 'placeholder', 'user', 'photo', 'job', 'location']);

            return $table->make(true);
        }

        return view('admin.mentors.index');
    }

    public function create()
    {
        abort_if(Gate::denies('mentor_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $jobs = Job::all()->pluck('name', 'id');

        $locations = Location::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.mentors.create', compact('users', 'jobs', 'locations'));
    }

    public function store(StoreMentorRequest $request)
    {
        $mentor = Mentor::create($request->all());
        $mentor->jobs()->sync($request->input('jobs', []));

        if ($request->input('photo', false)) {
            $mentor->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $mentor->id]);
        }

        return redirect()->route('admin.mentors.index');
    }

    public function edit(Mentor $mentor)
    {
        abort_if(Gate::denies('mentor_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $jobs = Job::all()->pluck('name', 'id');

        $locations = Location::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $mentor->load('user', 'jobs', 'location');

        return view('admin.mentors.edit', compact('users', 'jobs', 'locations', 'mentor'));
    }

    public function update(UpdateMentorRequest $request, Mentor $mentor)
    {
        $mentor->update($request->all());
        $mentor->jobs()->sync($request->input('jobs', []));

        if ($request->input('photo', false)) {
            if (!$mentor->photo || $request->input('photo') !== $mentor->photo->file_name) {
                $mentor->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
            }
        } elseif ($mentor->photo) {
            $mentor->photo->delete();
        }

        return redirect()->route('admin.mentors.index');
    }

    public function show(Mentor $mentor)
    {
        abort_if(Gate::denies('mentor_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $mentor->load('user', 'jobs', 'location');

        return view('admin.mentors.show', compact('mentor'));
    }

    public function destroy(Mentor $mentor)
    {
        abort_if(Gate::denies('mentor_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $mentor->delete();

        return back();
    }

    public function massDestroy(MassDestroyMentorRequest $request)
    {
        Mentor::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('mentor_create') && Gate::denies('mentor_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Mentor();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media', 'public');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

app/Http/Controllers/Mentor/MentorPageController.php
<?php

namespace App\Http\Controllers\Mentor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Mentor;
use App\Job;
use App\Location;
use Auth;


class MentorPageController extends Controller
{
 	
	public function getProfile (){

		$mentor = Mentor::where("user_id", Auth::user()->id)->get();

		$users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $jobs = Job::all()->pluck('name', 'id');

        $locations = Location::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $mentor = $mentor[0]->load('user', 'jobs', 'location');

        return view('front.profile_mentor.profile_mentor', compact('users', 'jobs', 'locations', 'mentor'));
	}

	public function profileUpdatePost (Request $request){

		$mentor = Mentor::where("user_id", Auth::user()->id)->get();

		$users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $jobs = Job::all()->pluck('name', 'id');

        $locations = Location::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $mentor = $mentor[0]->load('user', 'jobs', 'location');

		$data = request()->except(['_token', 'jobs', 'photo', 'mentor_name', 'mentor_surname']);

		$mentor->where("user_id", Auth::user()->id)
				->update($data);
        $mentor->jobs()->sync($request->input('jobs', []));

        User::where("id", Auth::user()->id)->update(["name" => $request->input('mentor_name'), "surname" => $request->input('mentor_surname')]);

        if ($request->input('photo', false)) {
            if (!$mentor->photo || $request->input('photo') !== $mentor->photo->file_name) {
                $data = getimagesize(storage_path('tmp/uploads/' . $request->input('photo')));
                $width = $data[0];
                $height = $data[1];
                if($width != $height){
                    return redirect()->back()->with('message', 'Ошибка: загрузите ровный квадрат для аватара (ширина фото = высота фото)');
                }
                $mentor->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
            }
        } elseif ($mentor->photo) {
            $mentor->photo->delete();
        }

		return back();
	}

}

resources/views/admin/mentors/index.blade.php
@extends('layouts.admin')
@section('content')
@can('mentor_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.mentors.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.mentor.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.mentor.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-Mentor">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.id') }}
                    </th>
                    <th>
                        APPROVED
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.user') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.photo') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.job') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.job_place') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.education') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.price') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.location') }}
                    </th>
                    <th>
                        {{ trans('cruds.mentor.fields.age') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('mentor_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.mentors.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.mentors.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'approved', name: 'approved' },
{ data: 'user_email', name: 'user.email' },
{ data: 'photo', name: 'photo', sortable: false, searchable: false },
{ data: 'job', name: 'jobs.name' },
{ data: 'job_place', name: 'job_place' },
{ data: 'education', name: 'education' },
{ data: 'price', name: 'price' },
{ data: 'location_name', name: 'location.name' },
{ data: 'age', name: 'age' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    order: [[ 1, 'desc' ]],
    pageLength: 25,
  };
  $('.datatable-Mentor').DataTable(dtOverrideGlobals);
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
});

</script>
@endsection

resources/views/admin/mentors/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.mentor.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.mentors.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.id') }}
                        </th>
                        <td>
                            {{ $mentor->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.user') }}
                        </th>
                        <td>
                            {{ $mentor->user->email ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.photo') }}
                        </th>
                        <td>
                            @if($mentor->photo)
                                <a href="{{ $mentor->photo->getUrl() }}" target="_blank">
                                    <img src="{{ $mentor->photo->getUrl('thumb') }}" width="50px" height="50px">
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.rating') }}
                        </th>
                        <td>
                            {{ $mentor->rating }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.speciality') }}
                        </th>
                        <td>
                            {{ $mentor->speciality }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.job') }}
                        </th>
                        <td>
                            @foreach($mentor->jobs as $key => $job)
                                <span class="label label-info">{{ $job->name }}</span>
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.job_place') }}
                        </th>
                        <td>
                            {{ $mentor->job_place }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.job_experience') }}
                        </th>
                        <td>
                            {{ $mentor->job_experience }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.education') }}
                        </th>
                        <td>
                            {{ $mentor->education }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.price') }}
                        </th>
                        <td>
                            {{ $mentor->price }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.contacts') }}
                        </th>
                        <td>
                            {{ $mentor->contacts }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.location') }}
                        </th>
                        <td>
                            {{ $mentor->location->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.age') }}
                        </th>
                        <td>
                            {{ $mentor->age }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.about') }}
                        </th>
                        <td>
                            {{ $mentor->about }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.useful_1') }}
                        </th>
                        <td>
                            {{ $mentor->useful_1 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.useful_2') }}
                        </th>
                        <td>
                            {{ $mentor->useful_2 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.useful_3') }}
                        </th>
                        <td>
                            {{ $mentor->useful_3 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.date_1') }}
                        </th>
                        <td>
                            {{ $mentor->date_1 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.date_2') }}
                        </th>
                        <td>
                            {{ $mentor->date_2 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.date_3') }}
                        </th>
                        <td>
                            {{ $mentor->date_3 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.date_4') }}
                        </th>
                        <td>
                            {{ $mentor->date_4 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.date_5') }}
                        </th>
                        <td>
                            {{ $mentor->date_5 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.online') }}
                        </th>
                        <td>
                            <input type="checkbox" disabled="disabled" {{ $mentor->online ? 'checked' : '' }}>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mentor.fields.offline') }}
                        </th>
                        <td>
                            <input type="checkbox" disabled="disabled" {{ $mentor->offline ? 'checked' : '' }}>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.mentors.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection