routes/web.php
<?php

//ФРОНТ ЧАСТЬ
/** Главная страница **/
Route::get('/', 'FrontPageController@index');

/* Текст договора */
Route::get('/oferta', 'FrontPageController@oferta');
Route::get('/oferta_kz', 'FrontPageController@oferta_kz');

/** Маршрут на страницу авторизации и регистрации */
Route::get('/auth', 'FrontPageController@auth');
Route::get('/user-register', 'FrontPageController@register');

Route::post('/register_post', 'FrontPageController@POSTregister');
Route::post('/auth_post', 'FrontPageController@POSTauth');

Route::get('/front-logout', 'FrontPageController@logout');

Route::get('/proffession/{id}', 'FrontPageController@jobPage');

Route::get('/search', 'FrontPageController@searchPage');

Route::get('/mentor_page/{id}', 'FrontPageController@mentorPage');


Route::group(['middleware' => ['auth.mentor'], 'prefix' => 'mentor'], function () {

    Route::any("/profile", "Mentor\MentorPageController@getProfile");
    Route::post("/profile-update-post", "Mentor\MentorPageController@profileUpdatePost");

});

Route::group(['middleware' => ['auth.user'], 'prefix' => 'user'], function () {

    Route::any("/profile", "User\UserPageController@getProfile");
    Route::post("/profile-update-post", "User\UserPageController@profileUpdatePost");

});




//БЭК ЧАСТЬ
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Mentors
    Route::delete('mentors/destroy', 'MentorsController@massDestroy')->name('mentors.massDestroy');
    Route::post('mentors/media', 'MentorsController@storeMedia')->name('mentors.storeMedia');
    Route::post('mentors/ckmedia', 'MentorsController@storeCKEditorImages')->name('mentors.storeCKEditorImages');
    Route::resource('mentors', 'MentorsController');

    // Clients
    Route::delete('clients/destroy', 'ClientsController@massDestroy')->name('clients.massDestroy');
    Route::post('clients/media', 'ClientsController@storeMedia')->name('clients.storeMedia');
    Route::post('clients/ckmedia', 'ClientsController@storeCKEditorImages')->name('clients.storeCKEditorImages');
    Route::resource('clients', 'ClientsController');

    // Jobs
    Route::delete('jobs/destroy', 'JobsController@massDestroy')->name('jobs.massDestroy');
    Route::post('jobs/media', 'JobsController@storeMedia')->name('jobs.storeMedia');
    Route::post('jobs/ckmedia', 'JobsController@storeCKEditorImages')->name('jobs.storeCKEditorImages');
    Route::resource('jobs', 'JobsController');

    // Locations
    Route::delete('locations/destroy', 'LocationsController@massDestroy')->name('locations.massDestroy');
    Route::resource('locations', 'LocationsController');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Job extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'jobs';

    protected $appends = [
        'photo',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public static $searchable = [
        'name',
        'about',
        'univer_1',
        'univer_2',
        'univer_3',
        'univer_4',
        'univer_5',
        'sub_job_1',
        'sub_job_2',
        'sub_job_3',
        'sub_job_4',
        'sub_job_5',
    ];

    protected $fillable = [
        'name',
        'about',
        'univer_1',
        'univer_2',
        'univer_3',
        'univer_4',
        'univer_5',
        'sub_job_1',
        'sub_job_2',
        'sub_job_3',
        'sub_job_4',
        'sub_job_5',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function getPhotoAttribute()
    {
        $file = $this->getMedia('photo')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }

    public function jobMentors()
    {
        return $this->belongsToMany(Mentor::class);
    }

}

app/Http/Controllers/Admin/JobsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyJobRequest;
use App\Http\Requests\StoreJobRequest;
use App\Http\Requests\UpdateJobRequest;
use App\Job;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class JobsController extends Controller
{
    use MediaUploadingTrait;

    public function index(Request $request)
    {
        if ($request->ajax()) {
            $query = Job::query()->select(sprintf('%s.*', (new Job)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'job_show';
                $editGate      = 'job_edit';
                $deleteGate    = 'job_delete';
                $crudRoutePart = 'jobs';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('photo', function ($row) {
                if ($photo = $row->photo) {
                    return sprintf(
                        '<a href="%s" target="_blank"><img src="%s" width="50px" height="50px"></a>',
                        $photo->url,
                        $photo->thumbnail
                    );
                }

                return '';
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->editColumn('univer_1', function ($row) {
                return $row->univer_1 ? $row->univer_1 : "";
            });
            $table->editColumn('univer_2', function ($row) {
                return $row->univer_2 ? $row->univer_2 : "";
            });
            $table->editColumn('univer_3', function ($row) {
                return $row->univer_3 ? $row->univer_3 : "";
            });
            $table->editColumn('univer_4', function ($row) {
                return $row->univer_4 ? $row->univer_4 : "";
            });
            $table->editColumn('univer_5', function ($row) {
                return $row->univer_5 ? $row->univer_5 : "";
            });
            $table->editColumn('sub_job_1', function ($row) {
                return $row->sub_job_1 ? $row->sub_job_1 : "";
            });
            $table->editColumn('sub_job_2', function ($row) {
                return $row->sub_job_2 ? $row->sub_job_2 : "";
            });
            $table->editColumn('sub_job_3', function ($row) {
                return $row->sub_job_3 ? $row->sub_job_3 : "";
            });
            $table->editColumn('sub_job_4', function ($row) {
                return $row->sub_job_4 ? $row->sub_job_4 : "";
            });
            $table->editColumn('sub_job_5', function ($row) {
                return $row->sub_job_5 ? $row->sub_job_5 : "";
            });

            $table->rawColumns(['actions', 'placeholder', 'photo']);

            return $table->make(true);
        }

        return view('admin.jobs.index');
    }

    public function create()
    {
        abort_if(Gate::denies('job_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.jobs.create');
    }

    public function store(StoreJobRequest $request)
    {
        $job = Job::create($request->all());

        if ($request->input('photo', false)) {
            $job->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $job->id]);
        }

        return redirect()->route('admin.jobs.index');
    }

    public function edit(Job $job)
    {
        abort_if(Gate::denies('job_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.jobs.edit', compact('job'));
    }

    public function update(UpdateJobRequest $request, Job $job)
    {
        $job->update($request->all());

        if ($request->input('photo', false)) {
            if (!$job->photo || $request->input('photo') !== $job->photo->file_name) {
                $job->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
            }
        } elseif ($job->photo) {
            $job->photo->delete();
        }

        return redirect()->route('admin.jobs.index');
    }

    public function show(Job $job)
    {
        abort_if(Gate::denies('job_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $job->load('jobMentors');

        return view('admin.jobs.show', compact('job'));
    }

    public function destroy(Job $job)
    {
        abort_if(Gate::denies('job_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $job->delete();

        return back();
    }

    public function massDestroy(MassDestroyJobRequest $request)
    {
        Job::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('job_create') && Gate::denies('job_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Job();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media', 'public');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/jobs/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.job.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.jobs.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.job.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', 'Не указано') }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="photo">Иконка профессии</label>
                <div class="needsclick dropzone {{ $errors->has('photo') ? 'is-invalid' : '' }}" id="photo-dropzone">
                </div>
                @if($errors->has('photo'))
                    <span class="text-danger">{{ $errors->first('photo') }}</span>
                @endif
                <span class="help-block">Иконка для профессии</span>
            </div>
            <div class="form-group">
                <label for="about">{{ trans('cruds.job.fields.about') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('about') ? 'is-invalid' : '' }}" name="about" id="about">{!! old('about') !!}</textarea>
                @if($errors->has('about'))
                    <span class="text-danger">{{ $errors->first('about') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.about_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="univer_1">{{ trans('cruds.job.fields.univer_1') }}</label>
                <input class="form-control {{ $errors->has('univer_1') ? 'is-invalid' : '' }}" type="text" name="univer_1" id="univer_1" value="{{ old('univer_1', 'Не указано') }}" required>
                @if($errors->has('univer_1'))
                    <span class="text-danger">{{ $errors->first('univer_1') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.univer_1_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="univer_2">{{ trans('cruds.job.fields.univer_2') }}</label>
                <input class="form-control {{ $errors->has('univer_2') ? 'is-invalid' : '' }}" type="text" name="univer_2" id="univer_2" value="{{ old('univer_2', 'Не указано') }}" required>
                @if($errors->has('univer_2'))
                    <span class="text-danger">{{ $errors->first('univer_2') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.univer_2_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="univer_3">{{ trans('cruds.job.fields.univer_3') }}</label>
                <input class="form-control {{ $errors->has('univer_3') ? 'is-invalid' : '' }}" type="text" name="univer_3" id="univer_3" value="{{ old('univer_3', 'Не указано') }}" required>
                @if($errors->has('univer_3'))
                    <span class="text-danger">{{ $errors->first('univer_3') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.univer_3_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="univer_4">{{ trans('cruds.job.fields.univer_4') }}</label>
                <input class="form-control {{ $errors->has('univer_4') ? 'is-invalid' : '' }}" type="text" name="univer_4" id="univer_4" value="{{ old('univer_4', 'Не указано') }}">
                @if($errors->has('univer_4'))
                    <span class="text-danger">{{ $errors->first('univer_4') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.univer_4_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="univer_5">{{ trans('cruds.job.fields.univer_5') }}</label>
                <input class="form-control {{ $errors->has('univer_5') ? 'is-invalid' : '' }}" type="text" name="univer_5" id="univer_5" value="{{ old('univer_5', 'Не указано') }}">
                @if($errors->has('univer_5'))
                    <span class="text-danger">{{ $errors->first('univer_5') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.univer_5_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sub_job_1">{{ trans('cruds.job.fields.sub_job_1') }}</label>
                <input class="form-control {{ $errors->has('sub_job_1') ? 'is-invalid' : '' }}" type="text" name="sub_job_1" id="sub_job_1" value="{{ old('sub_job_1', 'Не указано') }}" required>
                @if($errors->has('sub_job_1'))
                    <span class="text-danger">{{ $errors->first('sub_job_1') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.sub_job_1_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sub_job_2">{{ trans('cruds.job.fields.sub_job_2') }}</label>
                <input class="form-control {{ $errors->has('sub_job_2') ? 'is-invalid' : '' }}" type="text" name="sub_job_2" id="sub_job_2" value="{{ old('sub_job_2', 'Не указано') }}" required>
                @if($errors->has('sub_job_2'))
                    <span class="text-danger">{{ $errors->first('sub_job_2') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.sub_job_2_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sub_job_3">{{ trans('cruds.job.fields.sub_job_3') }}</label>
                <input class="form-control {{ $errors->has('sub_job_3') ? 'is-invalid' : '' }}" type="text" name="sub_job_3" id="sub_job_3" value="{{ old('sub_job_3', 'Не указано') }}" required>
                @if($errors->has('sub_job_3'))
                    <span class="text-danger">{{ $errors->first('sub_job_3') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.sub_job_3_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sub_job_4">{{ trans('cruds.job.fields.sub_job_4') }}</label>
                <input class="form-control {{ $errors->has('sub_job_4') ? 'is-invalid' : '' }}" type="text" name="sub_job_4" id="sub_job_4" value="{{ old('sub_job_4', 'Не указано') }}" required>
                @if($errors->has('sub_job_4'))
                    <span class="text-danger">{{ $errors->first('sub_job_4') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.sub_job_4_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sub_job_5">{{ trans('cruds.job.fields.sub_job_5') }}</label>
                <input class="form-control {{ $errors->has('sub_job_5') ? 'is-invalid' : '' }}" type="text" name="sub_job_5" id="sub_job_5" value="{{ old('sub_job_5', 'Не указано') }}" required>
                @if($errors->has('sub_job_5'))
                    <span class="text-danger">{{ $errors->first('sub_job_5') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.job.fields.sub_job_5_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.photoDropzone = {
    url: '{{ route('admin.jobs.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="photo"]').remove()
      $('form').append('<input type="hidden" name="photo" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="photo"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($job) && $job->photo)
      var file = {!! json_encode($job->photo) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $job->photo->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="photo" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/jobs/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', {{ $job->id ?? 0 }});
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/jobs/index.blade.php
@extends('layouts.admin')
@section('content')
@can('job_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.jobs.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.job.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.job.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-Job">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.job.fields.id') }}
                    </th>
                    <th>
                        Иконка
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.name') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.univer_1') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.univer_2') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.univer_3') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.univer_4') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.univer_5') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.sub_job_1') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.sub_job_2') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.sub_job_3') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.sub_job_4') }}
                    </th>
                    <th>
                        {{ trans('cruds.job.fields.sub_job_5') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('job_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.jobs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.jobs.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'photo', name: 'photo', sortable: false, searchable: false },
{ data: 'name', name: 'name' },
{ data: 'univer_1', name: 'univer_1' },
{ data: 'univer_2', name: 'univer_2' },
{ data: 'univer_3', name: 'univer_3' },
{ data: 'univer_4', name: 'univer_4' },
{ data: 'univer_5', name: 'univer_5' },
{ data: 'sub_job_1', name: 'sub_job_1' },
{ data: 'sub_job_2', name: 'sub_job_2' },
{ data: 'sub_job_3', name: 'sub_job_3' },
{ data: 'sub_job_4', name: 'sub_job_4' },
{ data: 'sub_job_5', name: 'sub_job_5' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    order: [[ 1, 'desc' ]],
    pageLength: 25,
  };
  $('.datatable-Job').DataTable(dtOverrideGlobals);
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
});

</script>
@endsection